version: '3.8'

services:
  lab-systemd:
    build: ./lab
    # isolamento mínimo para rodar systemd sem privilegiar
    runtime: sysbox-runc

    stdin_open: true
    tty: true

    mem_limit: 512M
    memswap_limit: 512M
    cpus: '1.0'

    volumes:
      - type: bind
        source: /etc/machine-id
        target: /etc/machine-id
        read_only: true

    tmpfs:
      - /run
      - /run/lock
      - /tmp

    command: ["/sbin/init"]
